### ISSUE TITLE
How use this ?

### ISSUE THREAD

**Issue by francoataffarel** [OSSystems/find-binary-version-rs#15]
Hello can u help me?

how can i use this?

**Comment by otavio** [comment]
We have a simple example code at https://github.com/OSSystems/find-binary-version-rs/blob/master/examples/find-binary-version.rs; one more advanced at https://github.com/UpdateHub/updatehub/blob/6bc1a96fc9e3c6354125b3a7438934664b38401e/updatehub/src/object/installer/mod.rs#L66-L78.
